eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: eureka-client
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
#  prefix: /v1