
spring:
  application:
    name: service-turbine
server:
  port: 8769
turbine:
  aggregator:
    clusterConfig: default
  app-config: eureka-ribbon-client,eureka-feign-client
  cluster-name-expression: new String("default")
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
